CREATE TABLE CAFE_MENU(
    MENU_ID NUMBER,
    MENU_NAME VARCHAR2(30) PRIMARY KEY,
    MENU_PRICE NUMBER NOT NULL,
    MENU_CATEGORY VARCHAR2(20)
);

CREATE TABLE CAFE_ORDER(
    ORDER_ID NUMBER PRIMARY KEY,
    ORDER_DATE DATE,
    CUSTOMER_ID NUMBER CONSTRAINT CUS_ID_FK REFERENCES CAFE_CUSTOMER(CUSTOMER_ID),
    CUSTOMER_NAME VARCHAR2(30),
    ORDER_NAME VARCHAR2(30) CONSTRAINT ORD_NAME_FK REFERENCES CAFE_MENU(MENU_NAME),
    ORDER_PRICE NUMBER NOT NULL,
    OPTION_NAME VARCHAR2(30) CONSTRAINT OPT_NAME_FK REFERENCES CAFE_OPTION(OPTION_NAME),
    OPTION_PRICE NUMBER,
    ORDER_CNT NUMBER NOT NULL,
    TOTAL_PRICE NUMBER NOT NULL,
    ORDER_PAYMENT VARCHAR2(20) CONSTRAINT PAYMENT_CHECK CHECK(ORDER_PAYMENT IN('카드','현금')),
    CUSTOMER_POINT NUMBER NOT NULL
);
CREATE TABLE CAFE_CUSTOMER(
    CUSTOMER_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(30),
    CUSTOMER_PHONE VARCHAR2(30),
    CUSTOMER_MIL NUMBER
);
CREATE TABLE CAFE_OPTION(
    OPTION_ID NUMBER,
    OPTION_NAME VARCHAR2(30) PRIMARY KEY,
    OPTION_PRICE NUMBER
);
CREATE TABLE CAFE_BASKET(
    BASKET_ID NUMBER,
    MENU_NAME VARCHAR2(30) CONSTRAINT BAS_MENU_FK REFERENCES CAFE_MENU(MENU_NAME),
    MENU_PRICE NUMBER,
    OPTION_NAME VARCHAR2(30) CONSTRAINT BAS_OPTION_FK REFERENCES CAFE_OPTION(OPTION_NAME),
    OPTION_PRICE NUMBER,
    MENU_CNT NUMBER,
    TOTAL_PRICE NUMBER
);

INSERT INTO CAFE_MENU VALUES(1, '핫아메리카노', 3000, 'COFFEE');
INSERT INTO CAFE_MENU VALUES(2,'아이스아메리카노', 3000, 'COFFEE');
INSERT INTO CAFE_MENU VALUES(3,'핫라떼', 4000, 'COFFEE');
INSERT INTO CAFE_MENU VALUES(4,'아이스라떼', 4000, 'COFFEE');
INSERT INTO CAFE_MENU VALUES(5,'핫카페모카', 4500, 'COFFEE');
INSERT INTO CAFE_MENU VALUES(6,'아이스카페모카', 4500, 'COFFEE');
INSERT INTO CAFE_MENU VALUES(7,'레몬에이드', 4500, 'ADE');
INSERT INTO CAFE_MENU VALUES(8,'복숭아에이드', 4500, 'ADE');
INSERT INTO CAFE_MENU VALUES(9,'초코케이크', 5000, 'DESSERT');
INSERT INTO CAFE_MENU VALUES(10,'와플', 3000, 'DESSERT');

SELECT * FROM CAFE_MENU;

INSERT INTO CAFE_OPTION VALUES(1, '샷 추가', 500);
INSERT INTO CAFE_OPTION VALUES(2, '선택 안함', 0);

INSERT INTO CAFE_CUSTOMER VALUES(4, '곰돌이', '1234', 0);
INSERT INTO CAFE_CUSTOMER VALUES(5, '곰순이', '5678', 0);